# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import spark_connector_pb2 as spark__connector__pb2


class Spark_ConnectorStub(object):
    """//////////////////////////////////////////
    //////////////RPC SERVICES////////////////
    //////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDirectorWork = channel.unary_unary(
                '/Spark_Connector/GetDirectorWork',
                request_serializer=spark__connector__pb2.Director.SerializeToString,
                response_deserializer=spark__connector__pb2.DirectorWork.FromString,
                )
        self.GetFamousActor = channel.unary_unary(
                '/Spark_Connector/GetFamousActor',
                request_serializer=spark__connector__pb2.Actor.SerializeToString,
                response_deserializer=spark__connector__pb2.ActorName.FromString,
                )


class Spark_ConnectorServicer(object):
    """//////////////////////////////////////////
    //////////////RPC SERVICES////////////////
    //////////////////////////////////////////

    """

    def GetDirectorWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFamousActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Spark_ConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDirectorWork': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDirectorWork,
                    request_deserializer=spark__connector__pb2.Director.FromString,
                    response_serializer=spark__connector__pb2.DirectorWork.SerializeToString,
            ),
            'GetFamousActor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFamousActor,
                    request_deserializer=spark__connector__pb2.Actor.FromString,
                    response_serializer=spark__connector__pb2.ActorName.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Spark_Connector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Spark_Connector(object):
    """//////////////////////////////////////////
    //////////////RPC SERVICES////////////////
    //////////////////////////////////////////

    """

    @staticmethod
    def GetDirectorWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Spark_Connector/GetDirectorWork',
            spark__connector__pb2.Director.SerializeToString,
            spark__connector__pb2.DirectorWork.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFamousActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Spark_Connector/GetFamousActor',
            spark__connector__pb2.Actor.SerializeToString,
            spark__connector__pb2.ActorName.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
