# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spark_connector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spark_connector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15spark_connector.proto\"\n\n\x08\x44irector\"\x07\n\x05\x41\x63tor\"!\n\x0f\x45xecutionResult\x12\x0e\n\x06output\x18\x01 \x01(\t2m\n\x0fSpark_Connector\x12.\n\x0fGetDirectorWork\x12\t.Director\x1a\x10.ExecutionResult\x12*\n\x0eGetFamousActor\x12\x06.Actor\x1a\x10.ExecutionResultb\x06proto3'
)




_DIRECTOR = _descriptor.Descriptor(
  name='Director',
  full_name='Director',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=35,
)


_ACTOR = _descriptor.Descriptor(
  name='Actor',
  full_name='Actor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=44,
)


_EXECUTIONRESULT = _descriptor.Descriptor(
  name='ExecutionResult',
  full_name='ExecutionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='ExecutionResult.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['Director'] = _DIRECTOR
DESCRIPTOR.message_types_by_name['Actor'] = _ACTOR
DESCRIPTOR.message_types_by_name['ExecutionResult'] = _EXECUTIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Director = _reflection.GeneratedProtocolMessageType('Director', (_message.Message,), {
  'DESCRIPTOR' : _DIRECTOR,
  '__module__' : 'spark_connector_pb2'
  # @@protoc_insertion_point(class_scope:Director)
  })
_sym_db.RegisterMessage(Director)

Actor = _reflection.GeneratedProtocolMessageType('Actor', (_message.Message,), {
  'DESCRIPTOR' : _ACTOR,
  '__module__' : 'spark_connector_pb2'
  # @@protoc_insertion_point(class_scope:Actor)
  })
_sym_db.RegisterMessage(Actor)

ExecutionResult = _reflection.GeneratedProtocolMessageType('ExecutionResult', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONRESULT,
  '__module__' : 'spark_connector_pb2'
  # @@protoc_insertion_point(class_scope:ExecutionResult)
  })
_sym_db.RegisterMessage(ExecutionResult)



_SPARK_CONNECTOR = _descriptor.ServiceDescriptor(
  name='Spark_Connector',
  full_name='Spark_Connector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=81,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDirectorWork',
    full_name='Spark_Connector.GetDirectorWork',
    index=0,
    containing_service=None,
    input_type=_DIRECTOR,
    output_type=_EXECUTIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFamousActor',
    full_name='Spark_Connector.GetFamousActor',
    index=1,
    containing_service=None,
    input_type=_ACTOR,
    output_type=_EXECUTIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPARK_CONNECTOR)

DESCRIPTOR.services_by_name['Spark_Connector'] = _SPARK_CONNECTOR

# @@protoc_insertion_point(module_scope)
