name := "MyGraphOperations"
version := "0.1.0"
scalaVersion := "2.12.13"
libraryDependencies += "org.apache.spark" %% "spark-graphx" % "2.4.5"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.5"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.5"