# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='anime.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61nime.proto\x1a\x0butils.proto\"i\n\tAnimeData\x12\x10\n\x08\x61nime_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61nime_title\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12\x14\n\x0c\x61nime_rating\x18\x04 \x01(\x01\x12\x0f\n\x07img_url\x18\x05 \x01(\t\"+\n\rAnimeDataList\x12\x1a\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\n.AnimeData\"$\n\x10\x41nimeByIdRequest\x12\x10\n\x08\x61nime_id\x18\x01 \x01(\t\"7\n\x12\x41nimeByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"?\n\x16\x41nimeByCategoryRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"5\n\x10GetAnimesRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\x32\xa4\x02\n\x05\x41nime\x12.\n\tGetAnimes\x12\x11.GetAnimesRequest\x1a\x0e.AnimeDataList\x12+\n\nSearchById\x12\x11.AnimeByIdRequest\x1a\n.AnimeData\x12\x33\n\x0cSearchByName\x12\x13.AnimeByNameRequest\x1a\x0e.AnimeDataList\x12;\n\x10SearchByCategory\x12\x17.AnimeByCategoryRequest\x1a\x0e.AnimeDataList\x12 \n\x08\x41\x64\x64\x41nime\x12\n.AnimeData\x1a\x08.Success\x12*\n\x0bRemoveAnime\x12\x11.AnimeByIdRequest\x1a\x08.Successb\x06proto3'
  ,
  dependencies=[utils__pb2.DESCRIPTOR,])




_ANIMEDATA = _descriptor.Descriptor(
  name='AnimeData',
  full_name='AnimeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='anime_id', full_name='AnimeData.anime_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anime_title', full_name='AnimeData.anime_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genres', full_name='AnimeData.genres', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anime_rating', full_name='AnimeData.anime_rating', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img_url', full_name='AnimeData.img_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=133,
)


_ANIMEDATALIST = _descriptor.Descriptor(
  name='AnimeDataList',
  full_name='AnimeDataList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='animes', full_name='AnimeDataList.animes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=178,
)


_ANIMEBYIDREQUEST = _descriptor.Descriptor(
  name='AnimeByIdRequest',
  full_name='AnimeByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='anime_id', full_name='AnimeByIdRequest.anime_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=216,
)


_ANIMEBYNAMEREQUEST = _descriptor.Descriptor(
  name='AnimeByNameRequest',
  full_name='AnimeByNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AnimeByNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='AnimeByNameRequest.max_results', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=273,
)


_ANIMEBYCATEGORYREQUEST = _descriptor.Descriptor(
  name='AnimeByCategoryRequest',
  full_name='AnimeByCategoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='AnimeByCategoryRequest.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='AnimeByCategoryRequest.max_results', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=338,
)


_GETANIMESREQUEST = _descriptor.Descriptor(
  name='GetAnimesRequest',
  full_name='GetAnimesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='GetAnimesRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='GetAnimesRequest.max_results', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=393,
)

_ANIMEDATALIST.fields_by_name['animes'].message_type = _ANIMEDATA
DESCRIPTOR.message_types_by_name['AnimeData'] = _ANIMEDATA
DESCRIPTOR.message_types_by_name['AnimeDataList'] = _ANIMEDATALIST
DESCRIPTOR.message_types_by_name['AnimeByIdRequest'] = _ANIMEBYIDREQUEST
DESCRIPTOR.message_types_by_name['AnimeByNameRequest'] = _ANIMEBYNAMEREQUEST
DESCRIPTOR.message_types_by_name['AnimeByCategoryRequest'] = _ANIMEBYCATEGORYREQUEST
DESCRIPTOR.message_types_by_name['GetAnimesRequest'] = _GETANIMESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnimeData = _reflection.GeneratedProtocolMessageType('AnimeData', (_message.Message,), {
  'DESCRIPTOR' : _ANIMEDATA,
  '__module__' : 'anime_pb2'
  # @@protoc_insertion_point(class_scope:AnimeData)
  })
_sym_db.RegisterMessage(AnimeData)

AnimeDataList = _reflection.GeneratedProtocolMessageType('AnimeDataList', (_message.Message,), {
  'DESCRIPTOR' : _ANIMEDATALIST,
  '__module__' : 'anime_pb2'
  # @@protoc_insertion_point(class_scope:AnimeDataList)
  })
_sym_db.RegisterMessage(AnimeDataList)

AnimeByIdRequest = _reflection.GeneratedProtocolMessageType('AnimeByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANIMEBYIDREQUEST,
  '__module__' : 'anime_pb2'
  # @@protoc_insertion_point(class_scope:AnimeByIdRequest)
  })
_sym_db.RegisterMessage(AnimeByIdRequest)

AnimeByNameRequest = _reflection.GeneratedProtocolMessageType('AnimeByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANIMEBYNAMEREQUEST,
  '__module__' : 'anime_pb2'
  # @@protoc_insertion_point(class_scope:AnimeByNameRequest)
  })
_sym_db.RegisterMessage(AnimeByNameRequest)

AnimeByCategoryRequest = _reflection.GeneratedProtocolMessageType('AnimeByCategoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANIMEBYCATEGORYREQUEST,
  '__module__' : 'anime_pb2'
  # @@protoc_insertion_point(class_scope:AnimeByCategoryRequest)
  })
_sym_db.RegisterMessage(AnimeByCategoryRequest)

GetAnimesRequest = _reflection.GeneratedProtocolMessageType('GetAnimesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETANIMESREQUEST,
  '__module__' : 'anime_pb2'
  # @@protoc_insertion_point(class_scope:GetAnimesRequest)
  })
_sym_db.RegisterMessage(GetAnimesRequest)



_ANIME = _descriptor.ServiceDescriptor(
  name='Anime',
  full_name='Anime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=396,
  serialized_end=688,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnimes',
    full_name='Anime.GetAnimes',
    index=0,
    containing_service=None,
    input_type=_GETANIMESREQUEST,
    output_type=_ANIMEDATALIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchById',
    full_name='Anime.SearchById',
    index=1,
    containing_service=None,
    input_type=_ANIMEBYIDREQUEST,
    output_type=_ANIMEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchByName',
    full_name='Anime.SearchByName',
    index=2,
    containing_service=None,
    input_type=_ANIMEBYNAMEREQUEST,
    output_type=_ANIMEDATALIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchByCategory',
    full_name='Anime.SearchByCategory',
    index=3,
    containing_service=None,
    input_type=_ANIMEBYCATEGORYREQUEST,
    output_type=_ANIMEDATALIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddAnime',
    full_name='Anime.AddAnime',
    index=4,
    containing_service=None,
    input_type=_ANIMEDATA,
    output_type=utils__pb2._SUCCESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveAnime',
    full_name='Anime.RemoveAnime',
    index=5,
    containing_service=None,
    input_type=_ANIMEBYIDREQUEST,
    output_type=utils__pb2._SUCCESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANIME)

DESCRIPTOR.services_by_name['Anime'] = _ANIME

# @@protoc_insertion_point(module_scope)
