# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\raccount.proto\"\xb1\x01\n\x18\x41llLikesAndViewsResponse\x12\x30\n\x10\x62ook_likes_views\x18\x01 \x01(\x0b\x32\x16.LikesAndViewsResponse\x12\x30\n\x10imdb_likes_views\x18\x02 \x01(\x0b\x32\x16.LikesAndViewsResponse\x12\x31\n\x11\x61nime_likes_views\x18\x03 \x01(\x0b\x32\x16.LikesAndViewsResponse\"5\n\x15LikesAndViewsResponse\x12\r\n\x05likes\x18\x01 \x03(\x03\x12\r\n\x05views\x18\x02 \x03(\x03\"\'\n\x14LikesAndViewsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x32\xa8\x02\n\x07\x41\x63\x63ount\x12G\n\x13GetAllLikesAndViews\x12\x15.LikesAndViewsRequest\x1a\x19.AllLikesAndViewsResponse\x12\x45\n\x14GetBookLikesAndViews\x12\x15.LikesAndViewsRequest\x1a\x16.LikesAndViewsResponse\x12\x45\n\x14GetIMDBLikesAndViews\x12\x15.LikesAndViewsRequest\x1a\x16.LikesAndViewsResponse\x12\x46\n\x15GetAnimeLikesAndViews\x12\x15.LikesAndViewsRequest\x1a\x16.LikesAndViewsResponseb\x06proto3'
)




_ALLLIKESANDVIEWSRESPONSE = _descriptor.Descriptor(
  name='AllLikesAndViewsResponse',
  full_name='AllLikesAndViewsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_likes_views', full_name='AllLikesAndViewsResponse.book_likes_views', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imdb_likes_views', full_name='AllLikesAndViewsResponse.imdb_likes_views', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anime_likes_views', full_name='AllLikesAndViewsResponse.anime_likes_views', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=195,
)


_LIKESANDVIEWSRESPONSE = _descriptor.Descriptor(
  name='LikesAndViewsResponse',
  full_name='LikesAndViewsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='likes', full_name='LikesAndViewsResponse.likes', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='views', full_name='LikesAndViewsResponse.views', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=250,
)


_LIKESANDVIEWSREQUEST = _descriptor.Descriptor(
  name='LikesAndViewsRequest',
  full_name='LikesAndViewsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='LikesAndViewsRequest.user_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=291,
)

_ALLLIKESANDVIEWSRESPONSE.fields_by_name['book_likes_views'].message_type = _LIKESANDVIEWSRESPONSE
_ALLLIKESANDVIEWSRESPONSE.fields_by_name['imdb_likes_views'].message_type = _LIKESANDVIEWSRESPONSE
_ALLLIKESANDVIEWSRESPONSE.fields_by_name['anime_likes_views'].message_type = _LIKESANDVIEWSRESPONSE
DESCRIPTOR.message_types_by_name['AllLikesAndViewsResponse'] = _ALLLIKESANDVIEWSRESPONSE
DESCRIPTOR.message_types_by_name['LikesAndViewsResponse'] = _LIKESANDVIEWSRESPONSE
DESCRIPTOR.message_types_by_name['LikesAndViewsRequest'] = _LIKESANDVIEWSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AllLikesAndViewsResponse = _reflection.GeneratedProtocolMessageType('AllLikesAndViewsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALLLIKESANDVIEWSRESPONSE,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:AllLikesAndViewsResponse)
  })
_sym_db.RegisterMessage(AllLikesAndViewsResponse)

LikesAndViewsResponse = _reflection.GeneratedProtocolMessageType('LikesAndViewsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LIKESANDVIEWSRESPONSE,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:LikesAndViewsResponse)
  })
_sym_db.RegisterMessage(LikesAndViewsResponse)

LikesAndViewsRequest = _reflection.GeneratedProtocolMessageType('LikesAndViewsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LIKESANDVIEWSREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:LikesAndViewsRequest)
  })
_sym_db.RegisterMessage(LikesAndViewsRequest)



_ACCOUNT = _descriptor.ServiceDescriptor(
  name='Account',
  full_name='Account',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=294,
  serialized_end=590,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllLikesAndViews',
    full_name='Account.GetAllLikesAndViews',
    index=0,
    containing_service=None,
    input_type=_LIKESANDVIEWSREQUEST,
    output_type=_ALLLIKESANDVIEWSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookLikesAndViews',
    full_name='Account.GetBookLikesAndViews',
    index=1,
    containing_service=None,
    input_type=_LIKESANDVIEWSREQUEST,
    output_type=_LIKESANDVIEWSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetIMDBLikesAndViews',
    full_name='Account.GetIMDBLikesAndViews',
    index=2,
    containing_service=None,
    input_type=_LIKESANDVIEWSREQUEST,
    output_type=_LIKESANDVIEWSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAnimeLikesAndViews',
    full_name='Account.GetAnimeLikesAndViews',
    index=3,
    containing_service=None,
    input_type=_LIKESANDVIEWSREQUEST,
    output_type=_LIKESANDVIEWSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCOUNT)

DESCRIPTOR.services_by_name['Account'] = _ACCOUNT

# @@protoc_insertion_point(module_scope)
