# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recommendationsBook_pb2 as recommendationsBook__pb2


class RecommendationsBookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendBook = channel.unary_unary(
                '/RecommendationsBook/RecommendBook',
                request_serializer=recommendationsBook__pb2.RecommendationBookRequest.SerializeToString,
                response_deserializer=recommendationsBook__pb2.RecommendationBookResponse.FromString,
                )
        self.SearchByName = channel.unary_unary(
                '/RecommendationsBook/SearchByName',
                request_serializer=recommendationsBook__pb2.BookNameRequest.SerializeToString,
                response_deserializer=recommendationsBook__pb2.RecommendationBookResponse.FromString,
                )
        self.SearchByCategory = channel.unary_unary(
                '/RecommendationsBook/SearchByCategory',
                request_serializer=recommendationsBook__pb2.BookCategoryRequest.SerializeToString,
                response_deserializer=recommendationsBook__pb2.RecommendationBookResponse.FromString,
                )
        self.GetBookById = channel.unary_unary(
                '/RecommendationsBook/GetBookById',
                request_serializer=recommendationsBook__pb2.BookByIdRequest.SerializeToString,
                response_deserializer=recommendationsBook__pb2.BookByIdResponse.FromString,
                )
        self.GetBookByCategory = channel.unary_unary(
                '/RecommendationsBook/GetBookByCategory',
                request_serializer=recommendationsBook__pb2.BookByCategoryRequest.SerializeToString,
                response_deserializer=recommendationsBook__pb2.BookByCategoryResponse.FromString,
                )


class RecommendationsBookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecommendBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationsBookServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendBook,
                    request_deserializer=recommendationsBook__pb2.RecommendationBookRequest.FromString,
                    response_serializer=recommendationsBook__pb2.RecommendationBookResponse.SerializeToString,
            ),
            'SearchByName': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByName,
                    request_deserializer=recommendationsBook__pb2.BookNameRequest.FromString,
                    response_serializer=recommendationsBook__pb2.RecommendationBookResponse.SerializeToString,
            ),
            'SearchByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByCategory,
                    request_deserializer=recommendationsBook__pb2.BookCategoryRequest.FromString,
                    response_serializer=recommendationsBook__pb2.RecommendationBookResponse.SerializeToString,
            ),
            'GetBookById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookById,
                    request_deserializer=recommendationsBook__pb2.BookByIdRequest.FromString,
                    response_serializer=recommendationsBook__pb2.BookByIdResponse.SerializeToString,
            ),
            'GetBookByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookByCategory,
                    request_deserializer=recommendationsBook__pb2.BookByCategoryRequest.FromString,
                    response_serializer=recommendationsBook__pb2.BookByCategoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecommendationsBook', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecommendationsBook(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecommendBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecommendationsBook/RecommendBook',
            recommendationsBook__pb2.RecommendationBookRequest.SerializeToString,
            recommendationsBook__pb2.RecommendationBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecommendationsBook/SearchByName',
            recommendationsBook__pb2.BookNameRequest.SerializeToString,
            recommendationsBook__pb2.RecommendationBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecommendationsBook/SearchByCategory',
            recommendationsBook__pb2.BookCategoryRequest.SerializeToString,
            recommendationsBook__pb2.RecommendationBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecommendationsBook/GetBookById',
            recommendationsBook__pb2.BookByIdRequest.SerializeToString,
            recommendationsBook__pb2.BookByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RecommendationsBook/GetBookByCategory',
            recommendationsBook__pb2.BookByCategoryRequest.SerializeToString,
            recommendationsBook__pb2.BookByCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
