# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendationsBook.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommendationsBook.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19recommendationsBook.proto\"A\n\x19RecommendationBookRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"4\n\x12\x42ookRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nbook_title\x18\x02 \x01(\t\"J\n\x1aRecommendationBookResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.BookRecommendation\"E\n\x0f\x42ookNameRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"M\n\x13\x42ookCategoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"D\n\x14\x42ookCategoryResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.BookRecommendation\"@\n\x10\x42ookNameResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.BookRecommendation2\xe5\x01\n\x13RecommendationsBook\x12H\n\rRecommendBook\x12\x1a.RecommendationBookRequest\x1a\x1b.RecommendationBookResponse\x12=\n\x0cSearchByName\x12\x10.BookNameRequest\x1a\x1b.RecommendationBookResponse\x12\x45\n\x10SearchByCategory\x12\x14.BookCategoryRequest\x1a\x1b.RecommendationBookResponseb\x06proto3'
)




_RECOMMENDATIONBOOKREQUEST = _descriptor.Descriptor(
  name='RecommendationBookRequest',
  full_name='RecommendationBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='RecommendationBookRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='RecommendationBookRequest.max_results', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=94,
)


_BOOKRECOMMENDATION = _descriptor.Descriptor(
  name='BookRecommendation',
  full_name='BookRecommendation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BookRecommendation.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='book_title', full_name='BookRecommendation.book_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=148,
)


_RECOMMENDATIONBOOKRESPONSE = _descriptor.Descriptor(
  name='RecommendationBookResponse',
  full_name='RecommendationBookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='RecommendationBookResponse.recommendations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=224,
)


_BOOKNAMEREQUEST = _descriptor.Descriptor(
  name='BookNameRequest',
  full_name='BookNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='BookNameRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='BookNameRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='BookNameRequest.max_results', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=295,
)


_BOOKCATEGORYREQUEST = _descriptor.Descriptor(
  name='BookCategoryRequest',
  full_name='BookCategoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='BookCategoryRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='BookCategoryRequest.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='BookCategoryRequest.max_results', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=374,
)


_BOOKCATEGORYRESPONSE = _descriptor.Descriptor(
  name='BookCategoryResponse',
  full_name='BookCategoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='BookCategoryResponse.recommendations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=444,
)


_BOOKNAMERESPONSE = _descriptor.Descriptor(
  name='BookNameResponse',
  full_name='BookNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='BookNameResponse.recommendations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=510,
)

_RECOMMENDATIONBOOKRESPONSE.fields_by_name['recommendations'].message_type = _BOOKRECOMMENDATION
_BOOKCATEGORYRESPONSE.fields_by_name['recommendations'].message_type = _BOOKRECOMMENDATION
_BOOKNAMERESPONSE.fields_by_name['recommendations'].message_type = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendationBookRequest'] = _RECOMMENDATIONBOOKREQUEST
DESCRIPTOR.message_types_by_name['BookRecommendation'] = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendationBookResponse'] = _RECOMMENDATIONBOOKRESPONSE
DESCRIPTOR.message_types_by_name['BookNameRequest'] = _BOOKNAMEREQUEST
DESCRIPTOR.message_types_by_name['BookCategoryRequest'] = _BOOKCATEGORYREQUEST
DESCRIPTOR.message_types_by_name['BookCategoryResponse'] = _BOOKCATEGORYRESPONSE
DESCRIPTOR.message_types_by_name['BookNameResponse'] = _BOOKNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendationBookRequest = _reflection.GeneratedProtocolMessageType('RecommendationBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONBOOKREQUEST,
  '__module__' : 'recommendationsBook_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationBookRequest)
  })
_sym_db.RegisterMessage(RecommendationBookRequest)

BookRecommendation = _reflection.GeneratedProtocolMessageType('BookRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECOMMENDATION,
  '__module__' : 'recommendationsBook_pb2'
  # @@protoc_insertion_point(class_scope:BookRecommendation)
  })
_sym_db.RegisterMessage(BookRecommendation)

RecommendationBookResponse = _reflection.GeneratedProtocolMessageType('RecommendationBookResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONBOOKRESPONSE,
  '__module__' : 'recommendationsBook_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationBookResponse)
  })
_sym_db.RegisterMessage(RecommendationBookResponse)

BookNameRequest = _reflection.GeneratedProtocolMessageType('BookNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOKNAMEREQUEST,
  '__module__' : 'recommendationsBook_pb2'
  # @@protoc_insertion_point(class_scope:BookNameRequest)
  })
_sym_db.RegisterMessage(BookNameRequest)

BookCategoryRequest = _reflection.GeneratedProtocolMessageType('BookCategoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOKCATEGORYREQUEST,
  '__module__' : 'recommendationsBook_pb2'
  # @@protoc_insertion_point(class_scope:BookCategoryRequest)
  })
_sym_db.RegisterMessage(BookCategoryRequest)

BookCategoryResponse = _reflection.GeneratedProtocolMessageType('BookCategoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOKCATEGORYRESPONSE,
  '__module__' : 'recommendationsBook_pb2'
  # @@protoc_insertion_point(class_scope:BookCategoryResponse)
  })
_sym_db.RegisterMessage(BookCategoryResponse)

BookNameResponse = _reflection.GeneratedProtocolMessageType('BookNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOKNAMERESPONSE,
  '__module__' : 'recommendationsBook_pb2'
  # @@protoc_insertion_point(class_scope:BookNameResponse)
  })
_sym_db.RegisterMessage(BookNameResponse)



_RECOMMENDATIONSBOOK = _descriptor.ServiceDescriptor(
  name='RecommendationsBook',
  full_name='RecommendationsBook',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=513,
  serialized_end=742,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecommendBook',
    full_name='RecommendationsBook.RecommendBook',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDATIONBOOKREQUEST,
    output_type=_RECOMMENDATIONBOOKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchByName',
    full_name='RecommendationsBook.SearchByName',
    index=1,
    containing_service=None,
    input_type=_BOOKNAMEREQUEST,
    output_type=_RECOMMENDATIONBOOKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchByCategory',
    full_name='RecommendationsBook.SearchByCategory',
    index=2,
    containing_service=None,
    input_type=_BOOKCATEGORYREQUEST,
    output_type=_RECOMMENDATIONBOOKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDATIONSBOOK)

DESCRIPTOR.services_by_name['RecommendationsBook'] = _RECOMMENDATIONSBOOK

# @@protoc_insertion_point(module_scope)
