version: "3.3"
services:

    account:
        container_name: account
        build: account
        image: account
        networks:
            - micro_services
        ports:
            - 50055:50055
            
    signin:
        container_name: signin
        environment:
            ACCOUNTS_HOST: account
        build: signin
        image: signin
        networks:
            - micro_services
        ports:
            - 50054:50054
            
    anime:
        container_name: anime
        build: anime
        image: anime
        networks:
            - micro_services
        ports:
            - 50053:50053
            
    book:
        container_name: book
        build: book
        image: book
        networks:
            - micro_services
        ports:
            - 50051:50051

    imdb:
        container_name: imdb
        build: imdb
        image: imdb
        networks:
            - micro_services
        ports:
            - 50052:50052

    library:
        container_name: library
        environment:
            ANIMES_HOST: anime
            BOOKS_HOST: book
            IMDBS_HOST: imdb
            ACCOUNTS_HOST: account
        build: library
        image: library
        networks:
            - micro_services
        ports:
            - 50050:50050
            
    api_gateway:
        container_name: api_gateway
        environment:
            LIBRARY_HOST: library
            SIGNIN_HOST: signin
        build: api_gateway
        image: api_gateway
        networks:
            - micro_services
        ports:
            - 5000:5000

networks:
    micro_services: