version : "3.8"
services:

    account:
        image: account
        networks:
            - microservices
        ports:
            - 50055:50055
    
    signin:
        environment:
            ACCOUNTS_HOST: account
        image: signin
        networks:
            - microservices
        ports:
            - 50054:50054

    anime:
        image: anime
        networks:
            - microservices
        ports:
            - 50053:50053

    book:
        image: book
        networks:
            - microservices
        ports:
            - 50051:50051

    imdb:
        image: imdb
        networks:
            - microservices
        ports:
            - 50052:50052

    library:
        environment:
            ANIMES_HOST: anime
            BOOKS_HOST: book
            IMDBS_HOST: imdb
            ACCOUNTS_HOST: account
        image: library
        networks:
            - microservices

    api_gateway:
        environment:
            LIBRARY_HOST: library
            SIGNIN_HOST: signin
        image: api_gateway
        networks:
            - microservices
        ports:
            - 5000:5000

networks:
    microservices: