version: "3.8"
services:

    account:
        build:
            dockerfile: Dockerfile
            context: ./account
        image: account
        networks:
            - micro_services
        ports:
            - 50055:50055

    signin:
        environment:
            ACCOUNTS_HOST: account
        build:
            dockerfile: Dockerfile
            context: ./signin
        image: signin
        networks:
            - micro_services
        ports:
            - 50054:50054

    anime:
        build:
            dockerfile: Dockerfile
            context: ./anime
        image: anime
        networks:
            - micro_services
        ports:
            - 50053:50053

    book:
        build:
            dockerfile: Dockerfile
            context: ./book
        image: book
        networks:
            - micro_services
        ports:
            - 50051:50051

    imdb:
        build:
            dockerfile: Dockerfile
            context: ./imdb
        image: imdb
        networks:
            - micro_services
        ports:
            - 50052:50052

    library:
        environment:
            BOOKS_HOST: book
            IMDBS_HOST: imdb
            ANIMES_HOST: anime
            ACCOUNTS_HOST: account

        build:
            dockerfile: Dockerfile
            context: ./library
        image: library
        networks:
            - micro_services
        ports:
            - 50050:50050

    api_gateway:
        environment:
            SIGNIN_HOST: signin
            LIBRARY_HOST: library
        build:
            dockerfile: Dockerfile
            context: ./api_gateway
        image: api_gateway
        networks:
            - micro_services
        ports:
            - 5000:5000

networks:
    micro_services: