# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils_pb2 as utils__pb2
import account_pb2 as account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='signin.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csignin.proto\x1a\x0butils.proto\x1a\raccount.proto2\x84\x01\n\x06SignIn\x12(\n\rGetUserByName\x12\x0c.UserRequest\x1a\t.UserData\x12*\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x08.Success\x12$\n\nDeleteUser\x12\x0c.UserRequest\x1a\x08.Successb\x06proto3'
  ,
  dependencies=[utils__pb2.DESCRIPTOR,account__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SIGNIN = _descriptor.ServiceDescriptor(
  name='SignIn',
  full_name='SignIn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=45,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserByName',
    full_name='SignIn.GetUserByName',
    index=0,
    containing_service=None,
    input_type=account__pb2._USERREQUEST,
    output_type=account__pb2._USERDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateUser',
    full_name='SignIn.UpdateUser',
    index=1,
    containing_service=None,
    input_type=account__pb2._UPDATEUSERREQUEST,
    output_type=utils__pb2._SUCCESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteUser',
    full_name='SignIn.DeleteUser',
    index=2,
    containing_service=None,
    input_type=account__pb2._USERREQUEST,
    output_type=utils__pb2._SUCCESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNIN)

DESCRIPTOR.services_by_name['SignIn'] = _SIGNIN

# @@protoc_insertion_point(module_scope)
